frr version 8.5
frr defaults traditional
hostname r2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
router bgp 65002
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 !
 neighbor 192.168.12.10 remote-as 65001
 neighbor 192.168.12.10 description BGP_PEER_R1
 neighbor 192.168.23.30 remote-as 65003
 neighbor 192.168.23.30 description BGP_PEER_R3
 !
 address-family ipv4 unicast
  network 10.0.0.2/32
  network 172.16.2.0/24
  neighbor 192.168.12.10 activate
  neighbor 192.168.12.10 route-map ALLOW-ALL in
  neighbor 192.168.12.10 route-map ALLOW-ALL out
  neighbor 192.168.23.30 activate
  neighbor 192.168.23.30 route-map ALLOW-ALL in
  neighbor 192.168.23.30 route-map ALLOW-ALL out
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
line vty
!
